### ISSUE TITLE
ClientProtocolException

### ISSUE THREAD

**Issue by D3S0X** [thelinmichael/spotify-web-api-java#139]
Hi, im trying to control spotify in my game with this api.
I want to test it manually. I do start then I log in with my account. After that  copy the code from the callback in my code and hotswap it. Then I do code. Alright, when i now do authorize now I get the following exception:

```Java
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:188)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.wrapper.spotify.SpotifyHttpManager.execute(SpotifyHttpManager.java:195)
	at com.wrapper.spotify.SpotifyHttpManager.post(SpotifyHttpManager.java:147)
	at com.wrapper.spotify.requests.AbstractRequest.postJson(AbstractRequest.java:131)
	at com.wrapper.spotify.requests.authorization.authorization_code.AuthorizationCodeRequest.execute(AuthorizationCodeRequest.java:34)
	at me.d3sox.client.commands.client.CommandTestCommand.execute(CommandTestCommand.java:55)
	at me.d3sox.client.commands.CommandListener.call(CommandListener.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at Start.main(Start.java:8)
```

```Java
Caused by: org.apache.http.HttpException: Unsupported cookie policy: default
	at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:150)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:131)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:193)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	... 24 more
```

This is my current code (Client ID and secret removed):

```Java
public class CommandTestCommand extends Command {

    private static final String clientId = "";
    private static final String clientSecret = "";
    private static final URI redirectUri = SpotifyHttpManager.makeUri("http://dererzfeind.xyz/callback");

    private static final SpotifyApi spotifyApi = new SpotifyApi.Builder()
            .setClientId(clientId)
            .setClientSecret(clientSecret)
            .setRedirectUri(redirectUri)
            .build();

    private static final AuthorizationCodeUriRequest authorizationCodeUriRequest = spotifyApi.authorizationCodeUri()
            .scope("user-read-birthdate,user-read-email")
            .show_dialog(true)
            .build();

    private static String code = "";
    private static AuthorizationCodeRequest authorizationCodeRequest = null;

    @Override
    public void execute(String[] args) {
        if (args.length == 1) {
            if (args[0].equalsIgnoreCase("start")) {
                final URI uri = authorizationCodeUriRequest.execute();
                ChatLogger.logChat("URI: " + uri.toString());
            } else if (args[0].equalsIgnoreCase("code")) {
                code = "";
                authorizationCodeRequest = spotifyApi.authorizationCode(code)
                        .build();
                ChatLogger.logChat("Code accepted");
            } else if (args[0].equalsIgnoreCase("authorize")) {
                ChatLogger.logChat("Authorizing...");
                try {
                    final AuthorizationCodeCredentials authorizationCodeCredentials = authorizationCodeRequest.execute();
                    spotifyApi.setAccessToken(authorizationCodeCredentials.getAccessToken());
                    spotifyApi.setRefreshToken(authorizationCodeCredentials.getRefreshToken());

                    ChatLogger.logChat("Done! Expires in: " + authorizationCodeCredentials.getExpiresIn());
                } catch (IOException | SpotifyWebApiException e) {
                    ChatLogger.logChat("Error: " + e.getMessage());
                    e.printStackTrace();
                }
            } else if (args[0].equalsIgnoreCase("skip")) {
                try {
                    SkipUsersPlaybackToNextTrackRequest request = spotifyApi.skipUsersPlaybackToNextTrack().build();
                    request.execute();
                } catch (IOException | SpotifyWebApiException e) {
                    e.printStackTrace();
                }
            }
        } else {
            ChatLogger.logChat(".test <start|code|authorize|skip>");
        }
        
    }
}
```

**Comment by D3S0X** [comment]
I tried some versions of HttpClient. On some i got the same error and on 4.5.5 and some others i got this error:
´´´Java
java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
´´´

**Comment by Dargmuesli** [comment]
You should not randomly try different versions. Kick all other versions of HttpClient than the one required out of your classpath. It looks like you have another version in it which is incompatible. Refer to https://github.com/aws/aws-sdk-java/issues/913 for details.
Closing, as this is not related to this wrapper itself. Feel free to further comment on this.
