### ISSUE TITLE
Race conditions in the date parsing?

### ISSUE THREAD

**Issue by I-Al-Istannen** [thelinmichael/spotify-web-api-java#140]
**Disclaimer:**
If I am a colossal idiot (I tend to be…), feel free to close this as an id10t error.

**Symptoms:**
The API crashes with a NumberFormatException, if all tracks of a playlist are fetched while another request concurrently fetches the playlist information. While you could and probably should work around that here, by just using the `Paging<PlaylistTrack>` the playlist request returns, the error might also happen in other circumstances.

**What I did already:**
This does not happen when manually stepping through with a debugger, which made me believe it could be timing related. An exception breakpoint finally revealed a call to `parseDouble`, which was correct, but was *passing invalid data* down to `readJavaFormatString`. Some more reading through the docs of [SimpleDateFormat](https://docs.oracle.com/javase/9/docs/api/java/text/SimpleDateFormat.html#synchronization) revealed this passage: `Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.`

To test this hypothesis, I replaced the `public static final SimpleDateFormat SIMPLE_DATE_FORMAT` causing it with my own subclass, which just synchronizes all methods against the object itself. This effectively stopped that error from happening, which sounds like it could have indeed been the culprit. While I was constrained by reflection, you can also explore `ThreadLocal` (as the docs suggested) or other solutions.

**Stacktrace:**

```
java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.text.DigitList.getDouble(DigitList.java:169)
	at java.text.DecimalFormat.parse(DecimalFormat.java:2056)
	at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1869)
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
	at java.text.DateFormat.parse(DateFormat.java:364)
	at com.wrapper.spotify.model_objects.specification.PlaylistTrack$JsonUtil.createModelObject(PlaylistTrack.java:146)
	at com.wrapper.spotify.model_objects.specification.PlaylistTrack$JsonUtil.createModelObject(PlaylistTrack.java:136)
	at com.wrapper.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObjectArray(AbstractModelObject.java:71)
	at com.wrapper.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObjectPaging(AbstractModelObject.java:120)
	at com.wrapper.spotify.model_objects.specification.Playlist$JsonUtil.createModelObject(Playlist.java:435)
	at com.wrapper.spotify.model_objects.specification.Playlist$JsonUtil.createModelObject(Playlist.java:378)
	at com.wrapper.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObject(AbstractModelObject.java:53)
	at com.wrapper.spotify.requests.data.playlists.GetPlaylistRequest.execute(GetPlaylistRequest.java:35)
	at com.wrapper.spotify.requests.data.playlists.GetPlaylistRequest.execute(GetPlaylistRequest.java:13)
->      at me.ialistannen.spotify.SpotifyApiHelperKt$toSingle$1.call(SpotifyApiHelper.kt:28)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:2846)
	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:11040)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:11040)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:463)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**MWE:**
```kotlin
import com.wrapper.spotify.SpotifyApi
import com.wrapper.spotify.model_objects.specification.Paging
import com.wrapper.spotify.model_objects.specification.Playlist
import com.wrapper.spotify.model_objects.specification.PlaylistTrack
import com.wrapper.spotify.requests.IRequest
import io.reactivex.Observable
import io.reactivex.Single
import io.reactivex.schedulers.Schedulers

fun main(args: Array<String>) {
    val url = "<playlist url>"
    val secret = "<client secret>"
    val id = "<client id>"

    val api = createSpotifyApi(secret, id)

    api.getPlaylistName(url.getUserAndPlaylistId())
            .subscribeOn(Schedulers.io())
            .subscribe {
                println("Name is: $it")
            }


    api.getPlaylistTracks(url.getUserAndPlaylistId())
            .map {
                it.track
            }.subscribe {
                println(it.name)
            }
}

private fun createSpotifyApi(clientSecret: String, clientId: String): SpotifyApi {
    val api = SpotifyApi.builder().setClientId(clientId).setClientSecret(clientSecret).build()

    val credentials = api.clientCredentials().build().execute()
    api.accessToken = credentials.accessToken

    return api
}


private fun String.getUserAndPlaylistId(): Pair<String, String> {
    val regex = Regex("user/(.+?)/playlist/(.+?)[^a-z0-9A-Z]")
    val match = regex.find(this) ?: throw IllegalArgumentException("Invalid link")
    val values = match.groupValues
    return values[1] to values[2]
}

private fun SpotifyApi.getPlaylistName(playlistData: Pair<String, String>): Observable<String> {
    return getPlaylist(playlistData.first, playlistData.second).build().toRxSingle<Playlist>()
            .toObservable()
            .map {
                it.name
            }
}

private fun <T> IRequest.toRxSingle(): Single<T> {
    return Single.fromCallable { this.execute() as T }
}


private fun SpotifyApi.getPlaylistTracks(playlistData: Pair<String, String>): Observable<PlaylistTrack> {
    return getPlaylistsTracks(playlistData.first, playlistData.second).build()
            .toRxSingle<Paging<PlaylistTrack>>()
            .toObservable()
            .flatMap {
                Observable.fromArray(*it.items)
            }
}
```

**Comment by Dargmuesli** [comment]
Thanks for the great description! Haven't seen such a detailed and properly formatted one in a long time :)
Unfortunately my time is very limited at the moment and threading is not my strength when it comes to Java. Because of that it will take me some time to fully understand and resolve this issue. Sorry about that. In the meantime you could go ahead and add more information if you find such. That would speed things up ;)
I have potential dumb question too: what does MWE mean? And what Java dialect is it that uses `fun` and `val`? Thanks in advance :)

**Comment by I-Al-Istannen** [comment]
I'm glad the format was alright :)

> Unfortunately my time is very limited at the moment and threading is not my strength when it comes to Java. Because of that it will take me some time to fully understand and resolve this issue. Sorry about that.

No problem at all :)

`MWE` stands for **M**inimum **W**orking **E**xample, i.e. the shortest amount of code that consistently reproduces the error. Maybe you know that as a [SSCCE](http://www.sscce.org/).
It is Kotlin code, I just copied it from my project and tweaked it a bit. I will append a rough translation to Java at the end of this comment, also removing the need for RxJava.

I am not sure what other data I could gather, as the error seems to be exactly that this `SimpleDateFormat` is shared between threads — an operation that is not safe. At least this is extremely likely, given the location of the error and the fact that the error stopped happening when I manually synchronized the date format.

A simple fix could be anything, from a synchronized subclass, from wrapping that date format in a synchronized block to managing it in a `ThreadLocal` and dealing with the fallout to other classes.
I changed the `SpotifyApi` class to this, for example, resolving the error as well:
```patch
--- a/src/main/java/com/wrapper/spotify/SpotifyApi.java
+++ b/src/main/java/com/wrapper/spotify/SpotifyApi.java
@@ -31,7 +31,9 @@ import com.wrapper.spotify.requests.data.users_profile.GetCurrentUsersProfileReq
 import com.wrapper.spotify.requests.data.users_profile.GetUsersProfileRequest;
 
 import java.net.URI;
+import java.text.ParseException;
 import java.text.SimpleDateFormat;
+import java.util.Date;
 import java.util.TimeZone;
 import java.util.logging.Logger;
 
@@ -81,8 +83,16 @@ public class SpotifyApi {
    * The date format used by the Spotify Web API. It uses the {@code GMT}  timezone and the following pattern:
    * {@code yyyy-MM-dd'T'HH:mm:ss}
    */
-  public static final SimpleDateFormat SIMPLE_DATE_FORMAT = makeSimpleDateFormat(
-          "yyyy-MM-dd'T'HH:mm:ss", "GMT");
+  private static final ThreadLocal<SimpleDateFormat> SIMPLE_DATE_FORMAT = ThreadLocal
+      .withInitial(() -> makeSimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", "GMT"));
+
+  public static Date parseDefaultDate(String input) throws ParseException {
+    return SIMPLE_DATE_FORMAT.get().parse(input);
+  }
+
+  public static String formatDefaultDate(Date date) {
+    return SIMPLE_DATE_FORMAT.get().format(date);
+  }
 
   private final IHttpManager httpManager;
   private final String scheme;
```
The correct way to solve that likely depends on the number of threads and how often you access it, if you need to fine tune performance. I don't know that about your application, so you'll have to decide that.


**MWE (java):**
```java
package me.ialistannen.spotify;

import com.wrapper.spotify.SpotifyApi;
import com.wrapper.spotify.model_objects.credentials.ClientCredentials;
import com.wrapper.spotify.model_objects.specification.PlaylistTrack;
import com.wrapper.spotify.requests.data.playlists.GetPlaylistRequest;
import com.wrapper.spotify.requests.data.playlists.GetPlaylistsTracksRequest;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.util.Pair;

public class ICrash {

  public static void main(String[] args) throws Exception {
    String url = "<playlist url>";
    String secret = "<client secret>";
    String id = "<client id>";

    SpotifyApi api = createSpotifyApi(secret, id);

    new Thread(() -> {
      try {
        String playlistName = getPlaylistName(api, getUserAndPlaylistId(url));
        System.out.println("Playlist name is: " + playlistName);
      } catch (Exception e) {
        e.printStackTrace();
      }
    }).start();

    for (PlaylistTrack track : getPlaylistTracks(api, getUserAndPlaylistId(url))) {
      System.out.println(track.getTrack().getName());
    }
  }

  private static SpotifyApi createSpotifyApi(String clientSecret, String clientId)
      throws Exception {
    SpotifyApi api = SpotifyApi.builder()
        .setClientId(clientId)
        .setClientSecret(clientSecret)
        .build();

    ClientCredentials credentials = api.clientCredentials().build().execute();
    api.setAccessToken(credentials.getAccessToken());

    return api;
  }

  private static Pair<String, String> getUserAndPlaylistId(String url) {
    Pattern regex = Pattern.compile("user/(.+?)/playlist/(.+?)[^a-z0-9A-Z]");
    Matcher matcher = regex.matcher(url);
    if (!matcher.find()) {
      throw new IllegalArgumentException("Invalid link");
    }

    return new Pair<>(matcher.group(1), matcher.group(2));
  }

  private static String getPlaylistName(SpotifyApi api,
      Pair<String, String> playlistData) throws Exception {
    GetPlaylistRequest request = api
        .getPlaylist(playlistData.getKey(), playlistData.getValue())
        .build();

    return request.execute().getName();
  }

  @SuppressWarnings("unchecked")
  private static List<PlaylistTrack> getPlaylistTracks(SpotifyApi api,
      Pair<String, String> playlistData) throws Exception {

    GetPlaylistsTracksRequest request = api
        .getPlaylistsTracks(playlistData.getKey(), playlistData.getValue())
        .build();

    return Arrays.asList(request.execute().getItems());
  }
}
```

**Comment by Dargmuesli** [comment]
In this project threading is only used for async execution in [SpotifyApiThreading](https://github.com/thelinmichael/spotify-web-api-java/blob/master/src/main/java/com/wrapper/spotify/SpotifyApiThreading.java). I understand the problem you described now, but I'm not sure what the appropriate way to implement a fix for this is. If you could submit a pull request, that would be great. And if you need more information about this project I'll gladly provide it!
In case you cannot submit a PR this is open for everyone else to contribute.

**Comment by Dargmuesli** [comment]
PR merged, keeping this open just in case we need further comments on this (but I don't think so ;)).

**Comment by JuanRomani** [comment]
Hi there!
I'm not sure if this is the proper way to ask about this but I'm getting "Invalid before cursor" using the GetCurrentUsersRecentlyPlayedTracksRequest.before() method... Is this issue related?

**Comment by Dargmuesli** [comment]
Could be, but I'm not sure why the error says something about cursors here. Please open another issue in which you describe the problem more detailed as with code examples and so on.

**Comment by Dargmuesli** [comment]
If you are not using Jitpack this issue is not related as this fix is not part of any release yet.

**Comment by Dargmuesli** [comment]
Version 2.0.2 was just released. I'll keep this issue another 4 days open.
