### ISSUE TITLE
Gson java.lang.IllegalStateException: Not a JSON Object

### ISSUE THREAD

**Issue by User3794739** [thelinmichael/spotify-web-api-java#160]
When calling `spotifyApi.getPlaylistCoverImage(id).build().execute()[0].getUrl();` Gson throws the exception in the issue title for `[{"height":null,"url":"https://pl.scdn.co/images/pl/default/93a22fe6a85d79c66a94350319e558678935b5d3","width":null}]` which seems to be valid JSON. Is that an issue on their side?

Complete Stacktrace:
`Exception in thread "main" java.lang.IllegalStateException: Not a JSON Object: [{"height":null,"url":"https://pl.scdn.co/images/pl/default/93a22fe6a85d79c66a94350319e558678935b5d3","width":null}]
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at com.wrapper.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:267)
	at com.wrapper.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:153)
	at com.wrapper.spotify.requests.AbstractRequest.getJson(AbstractRequest.java:117)
	at com.wrapper.spotify.requests.data.playlists.GetPlaylistCoverImageRequest.execute(GetPlaylistCoverImageRequest.java:33)`

**Comment by Dargmuesli** [comment]
Happy New Year! I'll have look into this soon.

**Comment by User3794739** [comment]
Indeed wrote that to copy and edit a new years playlist :P 
Thanks and happy new year too.

**Comment by Dargmuesli** [comment]
Should be good now, new release is coming :)
