### ISSUE TITLE
Build Fails on Android Studio 1.0.2

### ISSUE THREAD

**Issue by pcbmaster** [thelinmichael/spotify-web-api-java#29]
When I try to build my project, I get this error

```
FAILURE: Build failed with an exception.

    * What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
    /opt/android-sdk/build-tools/20.0.0/dx --dex --no-optimize --output     /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/dex/debug     /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/classes/debug     /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/support-annotations-21.0.2-1e9bba1e7979125665c442d859d2bfa58fa53060.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/spotify-web-api-android-0.1.0-fca8ee2b37af4c8fd880358ca39c51176d2bdde5.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/commons-codec-1.2-9cb6f7a99bfef71d74fdbf593c691f79fe52f88f.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/ezmorph-1.0.6-63ab713bf9aaac80f51ada3eb44a5c4dae7cb827.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/commons-beanutils-20030211.134440-ed02203e2b913d48dc67c294e8e9d2a005c0f248.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/spotify-web-api-java-1.5.0-cb15a384dc7e748b33b8e9c9dbb19c095623d263.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/gson-2.2.4-45eaac427fb9db50b682f13ce301f6dec56b70e7.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/internal_impl-21.0.2-72d2b2b92c5ad40a9a6555b931f108f2f9be435d.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/json-lib-2.4-jdk15-3429214c5d6c7f1ef41b701b00fd70d883bb4595.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/commons-httpclient-3.1-e86b344f6d58191c5e89f3aeeb7ebe48114bd18d.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/commons-lang-2.5-8b8d323f83fe48edf8dae63735500f986c1d4f01.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/commons-collections-3.2.1-ce7dadf96ddf836e820202aa77f47d4c43e866df.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/classes-32ad47a1c6cec698868b21d2fc53513df316dc96.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/protobuf-java-2.5.0-3cf24fbc9e056b732d53f56ca77af34f35d2b15b.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/classes-7671c176eaa1bf645a35219a5d65a175afb0d716.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/guava-18.0-96a33973037064bdc79abeceda82313dd1c27f46.jar /home/brett/AndroidStudioProjects/Perkisizer/app/build/intermediates/pre-dexed/debug/classes-506ba11a5d837e5be104f25a842725b6d5d59fd7.jar
  Error Code:
    2
  Output:

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: method ID not in [0, 0xffff]: 65536
    at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:501)
    at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:276)
    at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:490)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
    at com.android.dx.command.dexer.Main.run(Main.java:230)
    at com.android.dx.command.dexer.Main.main(Main.java:199)
    at com.android.dx.command.Main.main(Main.java:103)
```

**Comment by pcbmaster** [comment]
Also:

    :app:dexDebug
    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.IllegalArgumentException: method ID not in [0, 0xffff]: 65536
	    at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:501)
	    at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:276)
	    at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:490)
	    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
	    at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
	    at com.android.dx.command.dexer.Main.run(Main.java:230)
	    at com.android.dx.command.dexer.Main.main(Main.java:199)
	    at com.android.dx.command.Main.main(Main.java:103)

**Comment by digitaldesaster** [comment]
dont know if it belongs to this issue, but perhaps you have to modify your build.gradle

http://stackoverflow.com/questions/27458227/org-apache-commons-collections-arraystack-has-already-been-added-to-output-plea/27464289#27464289

compile('se.michaelthelin.spotify:spotify-web-api-java:1.5.0') {
        exclude group: "commons-beanutils", module: "commons-beanutils"

    }
    compile 'commons-beanutils:commons-beanutils:20030211.134440'

**Comment by pcbmaster** [comment]
I already had that in my build.gradle.  This seems to have something to do with logging:commons-logging:1.1.1

The full error log is here: http://pastebin.com/38zvbqDJ

**Comment by miguelpveloso** [comment]
Hello. I'm getting the same error. Is this because I'm using BuildToolVersion of 21.1.2? Gradle syncs fine, but when I run the app it gives me the same error pcbmaster has. Please help me asap, thanks a lot!

**Comment by Dargmuesli** [comment]
See the README note:

> You can use this library in your Android app. However, you should have a look at the [Android Wrapper](https://www.github.com/kaaes/spotify-web-api-android) project built by [kaaes](https://www.github.com/kaaes) as it's made specifically for Android. See also [Spotify's Android SDK](https://developer.spotify.com/technologies/spotify-android-sdk/

... and please reopen if this issue still exists.
