### ISSUE TITLE
Unable to get PlaylistTracksRequest with default api

### ISSUE THREAD

**Issue by DrunkCat159** [thelinmichael/spotify-web-api-java#86]
Api api = Api.DEFAULT_API; 

		// Create a request object for the type of request you want to make
		final PlaylistTracksRequest request = api.getPlaylistTracks("11182815951", "4fno11JmK8QAm55MWRq50v").build();
		 

		// Retrieve a playlist
		try {
		  
		  // Print the genres of the album
		  final List<PlaylistTrack> tracks = request.get().getItems();
//This one throwing an error? Am i doing it wrong?

**Comment by MDWay** [comment]
I have the same error 
Stacktrace: 

```java
Jun 24, 2017 6:21:51 PM org.apache.commons.httpclient.HttpMethodDirector processWWWAuthChallenge
WARNING: Unable to respond to any of these challenges: {bearer=Bearer realm="spotify"}
com.wrapper.spotify.exceptions.BadRequestException: 401
	at com.wrapper.spotify.SpotifyHttpManager.handleErrorStatusCode(SpotifyHttpManager.java:178)
	at com.wrapper.spotify.SpotifyHttpManager.execute(SpotifyHttpManager.java:157)
	at com.wrapper.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:53)
	at com.wrapper.spotify.methods.AbstractRequest.getJson(AbstractRequest.java:34)
	at com.wrapper.spotify.methods.PlaylistRequest.get(PlaylistRequest.java:37)
	at de.romjaki.discord.jda.commands.music.CommandPlayMusic.execute(CommandPlayMusic.java:125)
	at de.romjaki.discord.jda.MessageListener.lambda$processCommand$24(MessageListener.java:70)
	at java.lang.Thread.run(Thread.java:745)
```

> Note: 
> `de.romjaki.discord.jda.commands.music.CommandPlayMusic` and `de.romjaki.discord.jda.MessageListener` are my own classes

**Comment by Blake-Gao** [comment]
I believe that due to the new changes you need an access token now.

**Comment by Dargmuesli** [comment]
Correct. They were implemented in v2. Release date yet unknown.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
